#!/usr/bin/ruby

if($*[0] == nil)
	puts "Usage: sfdisk2parted /path/to/mydump.sfdisk"
	exit
end

bootvol = []
imgvol = []
begin
	File.open($*[0]).each { |line|
		if(!(line.include? "size"))
			next
		end
		part, attrs = line.split(':')
		part = part.rstrip.reverse.chr
		fields = attrs.split(',')
		if(part == "1")
			bootvol << fields[0].split('=')[1].lstrip.to_i
		end
		if(part == "2")
			p2start = fields[0].split('=')[1].lstrip.to_i
			p1end = p2start - 1
			p2end = fields[1].split('=')[1].lstrip.to_i + p1end
			bootvol << p1end
			imgvol << p2start
			imgvol << p2end
		end
	}
rescue Exception
	puts "Oops! Either could not open the file"
	puts
	puts " " + $*[0]
	puts
	puts "or it was not a proper sfdisk dump."
	exit
end

parts = "mkpart primary NTFS " + bootvol[0].to_s + "s " + bootvol[1].to_s + "s"
parts += " mkpart primary NTFS " + imgvol[0].to_s + "s " + imgvol[1].to_s + "s"

puts "Caveat partitioner! Assuming a TCC template style map,"
puts "with MSDOS disk label and two NTFS volumes:"
puts
puts "parted -sm /dev/sda mklabel msdos " + parts + " set 1 boot on"
puts
