#! /usr/bin/env python

from email.mime.text import MIMEText
from subprocess import Popen, PIPE
import sys
import socket

# Get pam_tally2 output and parse in to a nice format
import subprocess
import re

# Only run where we care
myhosts = ["rainbow", "login"]
shortname = socket.gethostname().split('.')[0]
if shortname not in hosts:
  sys.exit(0)

tally2output = iter(subprocess.check_output(("pam_tally2",
  "--reset")).split("\n"))

pattern = re.compile('\s*')

next(tally2output) # Discard header row
users = []
for lines in tally2output:
  if lines != "":
    user = pattern.split(lines)
    users.append(user)

message  = "Users who were bad at logging in today:\n\n"
message += "    user      times   last time/host\n"
message += "    --------------------------------\n"
count = 0

# Process users with bad histories
for user in users:
  # Field order: user, failure count, last failure, last host
  if int(user[1]) > 10:
    count += 1
    # This user was locked out and has not succeeded since then
    message += "    {0: <8}  {1: <8} {2} {3} @ {4}\n".format(user[0], user[1], user[2], user[3], user[4])

if count == 0:
  sys.exit()

message += "\n\nThe failed login log has been cleared."

# Send an email
msg = MIMEText(message)
msg["To"] = "root@nmt.edu"
msg["Subject"] = "Failed login report (" + shortname + ")"
p = Popen(["/usr/sbin/sendmail", "-t"], stdin=PIPE)
p.communicate(msg.as_string())
