#!/bin/bash

export SEMESTER="Spring2015"
export BRANCH="master"
export BUILD="1"
export LIBSYNC="http://update.nmt.edu/kickstart/21/libsync.sh"
export SYNCPRE="http://replicon.nmt.edu/images/Spring2015"
export BTHASH="6e4bec907c8efb58c62b108dc0fec9a62aee4ef1"
export OLDBTHASH="b5a12aa9e171547202864d7235d22a9b4526568d"
export WINMODE="Normal"

download_libsync() {

	wget -P /tmp $LIBSYNC > /dev/null 2>&1
	if [ -s "/tmp/libsync.sh" ]
	then
		return
	fi
	echo "Could not retrieve SYNC library!"
	exit 69 # EX_UNAVAILABLE from sysexits.h

}

download_libsync
source /tmp/libsync.sh
start_transmission
transmission-remote -t $OLDBTHASH --remove-and-delete
torrent_image
rm -f /tmp/libsync.sh
rm -f /tmp/$SEMESTER-$BRANCH.$BUILD.torrent
