#!/usr/bin/ruby

require 'fileutils'

path = "/fs/cameras"
uid = Process.uid.to_s
home = File.expand_path('~')
scratch = "/tmp/jpgmpg." + uid
out = home + "/jpgmpg"

unless `id -G`.split(' ').include?('26')
  puts "You must be in group tcc."
  exit(77) # EX_NOPERM
end

if $*.length == 0
  puts "Usage: jpgmpg <ENTRY [ENTRY]...>"
  puts
  puts "Format:  camera.date(YYYYMMDD).starthour(HH).endhour(HH)"
  puts "Examples:   speare16-cam.20050401.8.17  (8:00 through 17:59)"
  puts "           jonesa101-cam.20050401.0.23  (a whole day)"
  puts "         workman101-cam.20050401.12.12  (one hour only)"
  puts
  exit(64) # EX_USAGE
end

if not (File.directory?(path) and Dir.entries(path).length > 2)
  puts "Camera filesystem not mountable."
  exit(69) # EX_UNAVAILABLE
end

FileUtils.mkdir_p(scratch)
FileUtils.mkdir_p(out)

$*.each do |entry|
  params = entry.split('.')
  if params.length != 4
    puts "#{entry}: malformed"
    next
  end
  if not Dir.entries(path).include?(params[0])
    puts "#{entry}: unknown camera"
    next
  end
  if not Dir.entries(path + '/' + params[0]).include?(params[1])
    puts "#{entry}: nonarchived data"
    next
  end
  if params[2].to_i < 0 or params[3].to_i > 23 or params[2].to_i > params[3].to_i
    puts "#{entry}: incorrect hours"
    next
  end
  if params[2].length == 1; params[2] = "0" + params[2]; end
  if params[3].length == 1; params[3] = "0" + params[3]; end
  (params[2]..params[3]).to_a.each do |hour|
    this = [params[0], params[1], hour].join('.')
    Dir.chdir(path + '/' + params[0] + '/' + params[1]) {
      puts this + ': converting...'
      system("for jpg in $(ls *_2*_#{hour}*.jpg); do convert $jpg #{scratch}/$jpg.ppm; done")
      system("ls #{scratch}/*.ppm > #{scratch}/ppmlist")
      puts this + ': encoding...'
      system("sort #{scratch}/ppmlist | xargs -n1 cat | ppmtoy4m -S 420mpeg2 | mpeg2enc -v 0 -o #{out}/#{this}.mpg > /dev/null")
    }
    FileUtils.rm_f Dir.glob("#{scratch}/*")
  end
end

puts "Done. Your MPEG files are in ~/jpgmpg."
