#!/bin/bash

while :
do
	users=$(loginctl --no-legend list-users | grep -v "lightdm\|root" | wc -l)
	if [ "$users" -gt "0" ]
	then
		printf "ldmagain: active user sessions\n"
		break
	fi
	lastlog=$(journalctl --no-pager -u lightdm -o cat | grep "^pam" | tail -n 1)
	if [[ "$lastlog" =~ "pam".*"session opened".*"lightdm".* ]]
	then
		printf "ldmagain: lightdm running properly\n"
		break
	fi
	if [[ "$lastlog" =~ "pam".*"logname= ".* ]]
	then
		printf "ldmagain: restarting lightdm\n"
		systemctl restart lightdm
	fi
	sleep 10
done
