#!/bin/bash

prefix="/fs/tcc/boot_tools"

#make sure we have input
if [ "$1" = "" ]
then
	echo "Usage: make_bootusb /dev/sde"
	exit
else
	disk="$1"
fi

#make sure nothing is mounted
if [ "$(grep $disk /etc/mtab)" != "" ]
then
	echo "That device contains mounted filesystems."
	exit
fi

#let's double check what we are doing
echo -n "About to erase $disk, are you really sure? [YARLY]: "
read -e sure
if [ "$sure" != "YARLY" ]
then
	echo "Bailed out."
	exit
fi

#the dirty work
echo "You must authenticate as an ITC employee in"
echo "order to access the boot disk image file"
echo "(Kerberos will be used if possible)."
read -ep "Username: " user
mkdir /tmp/busb.$$
sshfs $user@userhost:$prefix /tmp/busb.$$
dd if=/tmp/busb.$$/bootcd.iso of=$disk bs=2048
fusermount -u /tmp/busb.$$
rmdir /tmp/busb.$$
echo "Done."
