#!/bin/bash

MAILTO="tcc-maint@nmt.edu, tcc-uc@nmt.edu"
ATTACH="/var/log/peripherals.log"

check_winpart() {

	systemctl start media-winpart.mount
	rm -f /media/winpart/ProgramData/PuppetLabs/puppet/var/state/agent_catalog_run.lock
	if [ -d "/media/winpart/Windows" ]
	then
		winfree=$(df --output=avail /media/winpart | sed -e '1d')
		hwinfree=$(df -h --output=avail /media/winpart | sed -e '1d')
		if [ "$winfree" -lt "4194304" ]
		then
			echo "$host is running out of room on its Windows partition ($hwinfree available)." | mail -s "$host: Windows low on space" $MAILTO
			
		fi
	fi
	systemctl stop media-winpart.mount

}

date > /var/log/peripherals.log
lsblk -ln >> /var/log/peripherals.log 2>&1
lsusb >> /var/log/peripherals.log 2>&1

host=$(hostname --short)
base="ou=clients,ou=machines,dc=tcc,dc=nmt,dc=edu"
staff=$(ldapsearch -xZZLLL -b ${base} cn=${host} tccOfficeMachine | sed -n -e '2p' | cut -d ":" -f 2)
staff=$(echo $staff)
tccos=$(ldapsearch -xZZLLL -b ${base} cn=${host} tccSpecialOS | sed -n -e '2p' | cut -d ":" -f 2)
tccos=$(echo $tccos)
room=$(echo $host | cut -d "-" -f 1)
building=$(echo $room | sed -e 's/[0-9]*//g')

if [ "$tccos" == "Linux" ]; then staff="TRUE"; fi
if [ "$building" == "library" ]; then staff="TRUE"; fi
if [ "$room" == "library208" ]; then staff="FALSE"; fi

if [ "$staff" == "FALSE" ]
then
	mouse=$(lsusb | grep "Mouse\|Logitech" | wc -l)
	kbd=$(lsusb | grep "Keyboard\|Cherry" | wc -l)
	odd=$(lsblk -ln | grep rom | wc -l)
	case $mouse in
		"0" )
			echo "$host does not have a USB mouse attached." | mail -s "$host: missing mouse" -a $ATTACH $MAILTO
			;;
		"1" )
			#these are not the droids you're looking for
			;;
		* )
			echo "$host has too many USB mice attached." | mail -s "$host: extra mouse" -a $ATTACH $MAILTO
			;;
	esac
	case $kbd in
		"0" )
			echo "$host does not have a USB keyboard attached." | mail -s "$host: missing keyboard" -a $ATTACH $MAILTO
			;;
		"1" )
			#he can go about his business
			;;
		* )
			echo "$host has too many USB keyboards attached." | mail -s "$host: extra keyboard" -a $ATTACH $MAILTO
			;;
	esac
	case $odd in
		"0" )
			echo "$host does not have an optical drive installed." | mail -s "$host: missing ODD" -a $ATTACH $MAILTO
			;;
		"1" )
			#move along
			;;
		* )
			echo "$host has too many optical drives installed." | mail -s "$host: extra ODD" -a $ATTACH $MAILTO
			;;
	esac

	winpart=$(/sbin/blkid -o device -t TYPE=ntfs)
	if [ "$winpart" != "" ]; then
		check_winpart
	fi
fi
