#!/bin/sh

# Terminate current user session
/bin/loginctl terminate-session $XDG_SESSION_ID
/usr/bin/killall --quiet --user $USER -SIGTERM gnome-keyring-daemon
/usr/bin/killall --quiet --user $USER -SIGTERM ssh-agent
/usr/bin/pax11publish -r
/usr/bin/killall --quiet --user $USER -SIGTERM pulseaudio

# Reset LightDM session settings
/bin/rm -f /var/lib/lightdm/.cache/lightdm-gtk-greeter/state
