#!/bin/bash

me=`hostname -s`

# Reboot instructor stations to Windows
if [ "${me: -4}" = "inst" ]
then
	exec /usr/local/bin/reboot_to_win
fi


# Reboot odd numbered computers to Windows
if [ $((${me: -1} % 2)) -eq 1 ]
then
	exec /usr/local/bin/reboot_to_win
fi
