#!/bin/bash

me=$(hostname -s)
base="ou=clients,ou=machines,dc=tcc,dc=nmt,dc=edu"
attr="tccSpecialOS"

# Reboot instructor stations to Windows
if [ "${me: -4}" = "inst" ]
then
	exec /usr/local/bin/reboot_to_win
fi

# Reboot odd numbered computers to Windows
if [ $((${me: -1} % 2)) -eq 1 ]
then
	exec /usr/local/bin/reboot_to_win
fi

sos=$(ldapsearch -xZZLLL -b $base cn=$me $attr | awk 'NR == 2 { print $2 }')

# Reboot tagged machines
if [ "$sos" == "Windows" ]
then
	exec /usr/local/bin/reboot_to_win
fi
