#!/bin/bash

export SEMESTER="Spring2015"
export BRANCH="master"
export BUILD="1"
export LIBSYNC="http://update.nmt.edu/kickstart/21/libsync.sh"
export SYNCPRE="http://replicon.nmt.edu/images/Spring2015"
export UNATTEND="/media/winpart/Windows/Panther/unattend.xml"
export WPCONF="/media/winpart/ProgramData/PuppetLabs/puppet/etc/puppet.conf"

download_libsync() {

	wget -P /tmp $LIBSYNC > /dev/null 2>&1
	if [ -s "/tmp/libsync.sh" ]
	then
		return
	fi
	dialog --backtitle "ITC $SEMESTER Kickstart" --title "SYNC" --msgbox "Could not retrieve SYNC library!" 5 36
	clear
	exit 69 # EX_UNAVAILABLE from sysexits.h

}

nofile() {

	dialog --backtitle "ITC $SEMESTER Kickstart" --title "SYNC" --msgbox "No local copy of template found!" 5 36
	clear
	exit 74 # EX_IOERR from sysexits.h

}

ntfs_check() {

	winpart=`/sbin/blkid -o device -t TYPE=ntfs`
	if [ "$winpart" == "" ]; then
		dialog --backtitle "ITC $SEMESTER Kickstart" --title "SYNC" --msgbox "No NTFS partitions were found!" 5 34
		clear
		exit 1
	fi

}

dialog --backtitle "ITC $SEMESTER Kickstart" --title "SYNC" --radiolist "Re-image Windows" 0 0 0 "Local" "Use locally stored copy of template" on "Network" "Unicast a new copy of the template" off 2> /tmp/reapply.$$

case "`cat /tmp/reapply.$$`" in
	Local)
		ntfs_check
		if [ ! -e "/var/lib/transmission/Downloads/$SEMESTER-$BRANCH.$BUILD/$SEMESTER-$BRANCH.$BUILD.vhd1" ]; then nofile; fi
		if [ ! -e "/var/lib/transmission/Downloads/$SEMESTER-$BRANCH.$BUILD/$SEMESTER-$BRANCH.$BUILD.vhd2.bz2" ]; then nofile; fi
		download_libsync
		source /tmp/libsync.sh
		apply_image
		;;
	Network)
		ntfs_check
		download_libsync
		source /tmp/libsync.sh
		unicast
		;;
	*)
		clear
		exit 0
		;;
esac
rm -f /tmp/libsync.sh

remctl puppet-win.nmt.edu puppet cert clean "`hostname -s`.tcc7"
systemctl start media-winpart.mount
if [ -e "$UNATTEND" ]
then
        sed -i -e "s/reference1/$(hostname -s)/" $UNATTEND
fi
if [ -e "$WPCONF" ]
then
        echo "certname=$(hostname -s).tcc7" >> $WPCONF
fi
systemctl stop media-winpart.mount

if [ "$1" != "--reboot" ]
then
        echo "Windows is ready to unroll. Reboot to continue."
else
        shutdown -r now
fi
