#!/bin/bash

function zap {
	rm -rf $1 >> ~/.nmtresetlog 2>&1
}

date=$(date)
host=$(hostname --short)
echo "reset_linux ($host): $date" >> ~/.nmtresetlog

echo "  Log out from all Linux graphical sessions before proceeding."
echo "  I will remove your Linux desktop environment settings, sessions,"
echo "  cache, and X authority files."
echo -n "Continue? <Y/n> "
read input

if [ "$input" != "Y" ]
then
	echo "Aborting per user request..."
	echo "Aborting per user request..." >> ~/.nmtresetlog
	exit
fi

zap ~/.cache
zap ~/.dmrc
zap ~/.ICEauthority
zap ~/.kde
zap ~/.local
zap ~/.gnome2
zap ~/.Xauthority
zap ~/.xsession-errors
zap ~/.config

echo "Done."
