#!/bin/bash

export SEMESTER="Fall2015"
export BRANCH="master"
export BUILD="1"
export LIBSYNC="http://duplicon.nmt.edu/preseed/jessie/libsync"
export SYNCPRE="http://template.nmt.edu/images/Fall2015"
export BTHASH="72aa0aab14bb5cd243fb6bdc2c383b477c523356"
export OLDBTHASH="6e4bec907c8efb58c62b108dc0fec9a62aee4ef1"
export WINMODE="Post"

download_libsync() {

	wget -P /tmp $LIBSYNC > /dev/null 2>&1
	if [ -s "/tmp/libsync" ]
	then
		return
	fi
	echo "Could not retrieve SYNC library!"
	exit 69 # EX_UNAVAILABLE from sysexits.h

}

download_libsync
source /tmp/libsync
start_transmission
transmission-remote -t $OLDBTHASH --remove-and-delete
sleep 2
transmission-remote -t $BTHASH --remove
sleep 2
torrent_image
rm -f /tmp/libsync
rm -f /tmp/$SEMESTER-$BRANCH.$BUILD.torrent
