#!/usr/bin/ruby

$id2fs = {
  "7" => "NTFS",
  "82" => "linux-swap",
  "83" => "ext4",
}

if($*[0] == nil)
  puts "Usage: sfdisk2parted /path/to/mydump.sfdisk"
  exit 66
end

begin
  File.open($*[0]).each { |line|
    if(!(line.include? "size"))
      next
    end
    line.gsub!(' ', '')
    part, attrs = line.split(':')
    start, size, id, flag = attrs.split(',')
    if(size == "size=0")
      next
    end
    output = "P" + part[-1, 1] + ": "
    type = id.split('=')[1].chomp
    if($id2fs.has_key?(type))
      output += $id2fs[type] + " "
    else
      output += "??? "
    end
    count = start.split('=')[1].to_i
    output += count.to_s + "s "
    output += (size.split('=')[1].to_i + (count - 1)).to_s + "s"
    puts output
  }
rescue Exception
  puts "Oops! Either could not open the file,"
  puts "or it was not a proper sfdisk dump."
  exit 74
end

puts
