#!/bin/sh

zap () {
	printf "  $1\n"
	rm -f $1 > /dev/null 2>&1
}

printf "Removing:\n"
zap ~/.mozilla/firefox/*.default/lock
zap ~/.mozilla/firefox/*.default/.parentlock
zap ~/.mozilla/default/*.slt/lock
zap ~/.config/google-chrome/SingletonLock
zap ~/.thunderbird/*.default/lock
zap ~/.thunderbird/*.default/.parentlock
