#!/usr/bin/env python3

import datetime
from email.mime.text import MIMEText
import pytz
import socket
import smtplib
import subprocess
import sys

# Only run where we care
myhosts = ["rainbow", "login"]
shortname = socket.gethostname().split(".")[0]
if shortname not in myhosts:
  sys.exit(0)

pamtally2 = subprocess.getoutput("/sbin/pam_tally2 --reset")
sshdjail = subprocess.getoutput("/usr/bin/fail2ban-client status sshd")
recidivejail = subprocess.getoutput("/usr/bin/fail2ban-client status recidive")

message  = "Users who were bad at logging in today:\n\n"
message += "{}\n\n".format(pamtally2)
message += "{}\n\n".format(sshdjail)
message += "{}\n".format(recidivejail)

# Send an email
tz = subprocess.getoutput('/bin/date +%z')
msg = MIMEText(message)
msg["To"] = "itc-eng@nmt.edu"
msg["From"] = "{}@nmt.edu".format(shortname)
msg["Subject"] = "Failed login report ({})".format(shortname)
msg["Date"] = datetime.datetime.now().strftime("%a, %d %b %Y %T ") + tz
s = smtplib.SMTP("localhost")
s.sendmail(msg["From"], [msg["To"]], msg.as_string())
s.quit()
