#!/bin/sh

ME=$(hostname -s)
DATE=$(date)
MAGIC="/var/run/lightdm/root/:0"

# Check if anybody is logged in on :0
ACCT=$(last -R -f /var/run/utmp :0 | awk 'NR == 1 { print $1 }')

# Bail if no one is
if [ -z "$ACCT" ]; then exit 0; fi

# Check if display is asleep
SCREEN=$(DISPLAY=:0 XAUTHORITY=$MAGIC xset -q | grep Monitor 2>/dev/null)

# Kick the user when both things were true
if [ "$SCREEN" == "Monitor is Off" ]
then
    loginctl terminate-user $ACCT
    printf "User $ACCT was kicked from $ME on $DATE.\n\nSincerely,\n$ME\n" | mail -r "$ME@nmt.edu" -s "$ME kicked a user" itc-uc@nmt.edu
fi
