#!/usr/bin/ruby

require 'socket'

body = ''
today = Time.now.strftime('%b %d')
['/var/log/auth.log.1', '/var/log/auth.log'].each do |log|
  File.readlines(log).each do |line|
    if (line =~ /sudoers/) and (line =~ /#{today}/)
      body += line
    end
  end
end

unless body.empty?
  subject = "** SECURITY information for #{Socket.gethostname} **"
  system("echo \"#{body}\" | s-nail -s '#{subject}' itc-eng@nmt.edu")
end
