#!/bin/bash

if [ -e "/usr/local/etc/template.conf" ]
then
	. /usr/local/etc/template.conf
else
	printf "Could not read deployment configuration!\n"
	exit 66 # EX_NOINPUT from sysexits.h
fi

export UNATTEND="/media/winpart/Windows/Panther/unattend.xml"
export WPCONFDIR="/media/winpart/ProgramData/PuppetLabs/puppet/etc"

download_libsync () {

	curl -s $PRESEED/libsync -o /tmp/libsync > /dev/null 2>&1
	if [ -s "/tmp/libsync" ]
	then
		return
	fi
	dialog --backtitle "ITC $SEMESTER Debian install" --title "SYNC" --msgbox "Could not retrieve SYNC library!" 5 36
	clear
	exit 69 # EX_UNAVAILABLE from sysexits.h

}

download_wpconf () {

	curl -s $PRESEED/winpuppet.conf -o /tmp/winpuppet.conf > /dev/null 2>&1
	if [ -s "/tmp/winpuppet.conf" ]
	then
		return
	fi
	dialog --backtitle "ITC $SEMESTER Debian install" --title "SYNC" --msgbox "Could not retrieve puppet configuration!" 5 44
	clear
	exit 69 # EX_UNAVAILABLE from sysexits.h

}

nofile () {

	dialog --backtitle "ITC $SEMESTER Debian install" --title "SYNC" --msgbox "No local copy of template found!" 5 36
	clear
	exit 74 # EX_IOERR from sysexits.h

}

ntfs_check () {

	winpart=$(/sbin/blkid -o device -t TYPE=ntfs)
	if [ "$winpart" == "" ]
	then
		dialog --backtitle "ITC $SEMESTER Debian install" --title "SYNC" --msgbox "No NTFS partitions were found!" 5 34
		clear
		exit 1
	fi

}

preunroll () {

	systemctl start media-winpart.mount
	if [ -e "$UNATTEND" ]
	then
		sed -i -e "s/reference1/$(hostname -s)/" $UNATTEND
	fi
	if [ -d "$WPCONFDIR" ]
	then
		rm -rf $WPCONFDIR/ssl > /dev/null 2>&1
		echo "certname=$(hostname -s).win7" >> /tmp/winpuppet.conf
		cat /tmp/winpuppet.conf > $WPCONFDIR/puppet.conf
	fi
	systemctl stop media-winpart.mount

}

if [ "$1" == "--preunroll" ]
then
	download_wpconf
	preunroll
	exit 0
fi

echo "You must authenticate as an ITC employee in order to clear this host's Puppet certificate."
read -p "Username: " login
kinit $login

dialog --backtitle "ITC $SEMESTER Debian install" --title "SYNC" --radiolist "Re-image Windows" 0 0 0 "Local" "Use locally stored copy of template" on "Network" "Unicast a new copy of the template" off 2> /tmp/reapply.$$

case "$(cat /tmp/reapply.$$)" in
	Local)
		ntfs_check
		if [ ! -e "/var/lib/transmission-daemon/downloads/$SEMESTER-$BRANCH.$BUILD/$SEMESTER-$BRANCH.$BUILD.vhd1" ]; then nofile; fi
		if [ ! -e "/var/lib/transmission-daemon/downloads/$SEMESTER-$BRANCH.$BUILD/$SEMESTER-$BRANCH.$BUILD.vhd2.bz2" ]; then nofile; fi
		download_libsync
		download_wpconf
		source /tmp/libsync
		apply_image
		;;
	Network)
		ntfs_check
		download_libsync
		download_wpconf
		source /tmp/libsync
		unicast
		;;
	*)
		clear
		exit 0
		;;
esac
rm -f /tmp/libsync

remctl puppet-win.nmt.edu puppet cert clean "$(hostname -s).tcc7"
preunroll
kdestroy -A

if [ "$1" != "--reboot" ]
then
	echo "Windows is ready to unroll. Reboot to continue."
else
	systemctl reboot
fi
