#!/usr/bin/ruby

case ARGV[0]
  when "windows"
    puts "Rebooting to Windows"
    system("/usr/local/bin/set_next_os 1 1")
    system("/usr/local/libexec/remreboot poof")
  when "poof"
    Process.daemon
    sleep(2)
    system("systemctl reboot")
  else
    puts "Rebooting to Linux"
    system("/usr/local/bin/set_next_os 0 1")
    system("/usr/local/libexec/remreboot poof")
end
