#!/usr/bin/env python

import remctl
import json
import datetime
import time,random
import argparse

if __name__ == '__main__':
	parser = argparse.ArgumentParser(
		description = "List all TCC Forge overlays"
	)
	parser.add_argument(
		'-n',
		'--now',
		action = "store_false",
		default = True,
		dest = 'now',
		help = 'skip the random wait'
	)
	cmdlineopts = parser.parse_args()
	if cmdlineopts.now:
		timeout = random.randint(0, 2 * 60 * 10) * 0.1
		time.sleep(timeout)
	command = ('forge','overlay','list','{"group":"tcc","distro":"F19"}')
	c = remctl.remctl(host = 'update.nmt.edu', command=command)
	r = json.loads(c.stdout)
	for overlay in r:
		print overlay["name"]
